from fastapi import APIRouter, Depends, HTTPException, status, UploadFile, File
from sqlalchemy.orm import Session
from sqlalchemy import and_
from typing import List, Optional
from datetime import datetime
import json
import os
import pandas as pd
import io
from app import models, schemas
from app.dependencies import get_db, get_current_user

router = APIRouter()

CACHE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data_cache")

def get_teacher_cache_file(teacher_id: int):
    return os.path.join(CACHE_DIR, f"teacher_{teacher_id}_tags.json")

@router.get("/tags")
def get_tags(
    refresh: bool = False,
    db: Session = Depends(get_db),
    current_user_data: dict = Depends(get_current_user)
):
    """
    获取当前教师的所有标签。
    如果 refresh=True，强制从数据库读取并更新缓存。
    否则优先读取缓存。
    """
    user_type = current_user_data.get("user_type")
    if user_type != "teacher":
        raise HTTPException(status_code=403, detail="Only teachers can access syllabus")
    
    teacher_id = current_user_data["user"].id
    cache_file = get_teacher_cache_file(teacher_id)
    
    # Ensure cache dir exists
    os.makedirs(CACHE_DIR, exist_ok=True)

    # If not refreshing and cache exists, return cache
    if not refresh and os.path.exists(cache_file):
        try:
            with open(cache_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"Error reading cache: {e}")
            # Fallback to DB
    
    # Fetch from DB
    tags = db.query(models.KnowledgeTag).filter(models.KnowledgeTag.teacher_id == teacher_id).all()
    data = []
    for tag in tags:
        data.append({
            "id": tag.id, # Keep ID for reference, though frontend might generate temp IDs for new ones
            "subject": tag.subject,
            "chapter": tag.chapter,
            "knowledge_point": tag.knowledge_point
        })
    
    # Write to cache
    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    return data

@router.post("/tags/save")
def save_tags(
    tags: List[dict],
    db: Session = Depends(get_db),
    current_user_data: dict = Depends(get_current_user)
):
    """
    保存标签：
    1. 更新缓存 JSON
    2. 更新数据库 (全量替换该教师的标签)
    """
    user_type = current_user_data.get("user_type")
    if user_type != "teacher":
        raise HTTPException(status_code=403, detail="Only teachers can access syllabus")
    
    teacher_id = current_user_data["user"].id
    teacher_subject = current_user_data["user"].subject
    print(f"Saving tags for teacher {teacher_id}, subject: {teacher_subject}. Count: {len(tags)}")
    
    cache_file = get_teacher_cache_file(teacher_id)
    
    # 1. Update Cache
    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump(tags, f, ensure_ascii=False, indent=2)
        
    # 2. Update Database
    try:
        # Delete existing tags for this teacher
        # We use synchronize_session=False because we are going to commit anyway
        db.query(models.KnowledgeTag).filter(models.KnowledgeTag.teacher_id == teacher_id).delete(synchronize_session=False)
        
        # Insert new tags
        new_objects = []
        for item in tags:
            # Requirement: id is auto-generated by DB, so we don't set it.
            # Requirement: teacher_id is the current teacher's id.
            # Requirement: subject is the teacher's subject.
            
            # Use teacher's subject. If the item has a subject (e.g. from previous load), we could use it,
            # but the requirement says "subject is this teacher's subject". 
            # So we strictly enforce teacher's subject to ensure consistency.
            subject = teacher_subject
            
            # Validate required fields
            chapter = item.get("chapter")
            knowledge_point = item.get("knowledge_point")
            
            if not chapter or not knowledge_point:
                continue # Skip invalid entries
            
            new_tag = models.KnowledgeTag(
                teacher_id=teacher_id,
                subject=subject,
                chapter=str(chapter).strip(),
                knowledge_point=str(knowledge_point).strip()
            )
            new_objects.append(new_tag)
            
        if new_objects:
            db.add_all(new_objects)
            
        db.commit()
        print(f"Successfully saved {len(new_objects)} tags to DB for teacher {teacher_id}.")
        return {"message": "Tags saved successfully", "count": len(new_objects)}
    except Exception as e:
        print(f"Error saving tags to DB: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")

@router.post("/import/excel")
async def import_excel(
    file: UploadFile = File(...),
    current_user_data: dict = Depends(get_current_user)
):
    """
    解析 Excel 文件并返回数据列表。
    不直接保存到数据库，由前端确认后保存。
    """
    user_type = current_user_data.get("user_type")
    if user_type != "teacher":
        raise HTTPException(status_code=403, detail="Only teachers can access syllabus")
    
    if not file.filename.endswith(('.xlsx', '.xls')):
        raise HTTPException(status_code=400, detail="Invalid file format. Please upload .xlsx or .xls")
    
    try:
        contents = await file.read()
        df = pd.read_excel(io.BytesIO(contents))
        
        # Normalize columns: strip whitespace
        df.columns = df.columns.str.strip()
        
        # Handle common typos
        if 'knowledege_point' in df.columns:
            df.rename(columns={'knowledege_point': 'knowledge_point'}, inplace=True)
            
        # Check headers
        required_columns = ['chapter', 'knowledge_point']
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
             raise HTTPException(status_code=400, detail=f"Missing columns. Required: {required_columns}. Missing: {missing_columns}. Found: {list(df.columns)}")
        
        # Extract data
        result = []
        for _, row in df.iterrows():
            result.append({
                "chapter": str(row['chapter']).strip(),
                "knowledge_point": str(row['knowledge_point']).strip()
            })
            
        return result
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing file: {str(e)}")


